using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.TrackBar;

namespace Thiet_ke.Objects
{
    public class ListSBTeacher : ISerializable
    {

        private SBTeacher[] bangDiemGVs = new SBTeacher[18];
        //Thuộc tính để truy xuất và thay đổi mảng bangDiemGVs từ bên ngoài.
        public SBTeacher[] BangDiemGVs
        {
            get { return bangDiemGVs; }
            set { bangDiemGVs = value; }
        }
        public ListSBTeacher() { }
        public void GetObjectData(SerializationInfo info, StreamingContext context)
        {
            // Thêm dữ liệu của thuộc tính `BangDiemGVs` vào `SerializationInfo` để tuần tự hóa
            info.AddValue("BangDiemGVs", BangDiemGVs);
        }
        public ListSBTeacher(SerializationInfo info, StreamingContext context)
        {
            // Lấy mảng `BangDiemGVs` đã được tuần tự hóa và gán lại cho thuộc tính `BangDiemGVs`
            BangDiemGVs = (SBTeacher[])info.GetValue("BangDiemGVs", typeof(SBTeacher[]));
        }
        // Tạo một mảng các đối tượng SBTeacher với các bản ghi mẫu cho bảng điểm giáo viên,
        // chứa thông tin về mã giáo viên, mã lớp, mã học sinh, học kỳ, điểm giữa kỳ, điểm cuối kỳ, và điểm tổng kết.
        public SBTeacher[] taoDSBDGV()
        {
            SBTeacher[] bangDiemGVs = new SBTeacher[]
                {
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A1", maHS ="HS1",maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A1", maHS ="HS2",maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A1", maHS ="HS3",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A2", maHS ="HS4",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A2", maHS ="HS5",maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A2", maHS ="HS6",maHK ="Học kỳ I", diemGiuaKy =2, diemCuoiKy =9, diemTongKet =5.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A1", maHS ="HS7",maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A1", maHS ="HS8",maHK ="Học kỳ I", diemGiuaKy =2, diemCuoiKy =9, diemTongKet =5.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A1", maHS ="HS9",maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =9, diemTongKet =6.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A2", maHS ="HS10",maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A2", maHS ="HS11",maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A2", maHS ="HS12",maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A1", maHS ="HS13",maHK ="Học kỳ I", diemGiuaKy =2, diemCuoiKy =9, diemTongKet =5.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A1", maHS ="HS14",maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A1", maHS ="HS15",maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A2", maHS ="HS16",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A2", maHS ="HS17",maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A2", maHS ="HS18",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},

                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A1", maHS ="HS1",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A1", maHS ="HS2",maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A1", maHS ="HS3",maHK ="Học kỳ II", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A2", maHS ="HS4",maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A2", maHS ="HS5",maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =4, diemTongKet =6},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L10A2", maHS ="HS6",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A1", maHS ="HS7",maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A1", maHS ="HS8",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A1", maHS ="HS9",maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A2", maHS ="HS10",maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A2", maHS ="HS11",maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L11A2", maHS ="HS12",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A1", maHS ="HS13",maHK ="Học kỳ II", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A1", maHS ="HS14",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A1", maHS ="HS15",maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A2", maHS ="HS16",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A2", maHS ="HS17",maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVTOAN", maLop = "2024L12A2", maHS ="HS18",maHK ="Học kỳ II", diemGiuaKy = 3, diemCuoiKy =9, diemTongKet =6},

                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A1", maHS ="HS1",maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A1", maHS ="HS2",maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A1", maHS ="HS3",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A2", maHS ="HS4",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A2", maHS ="HS5",maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A2", maHS ="HS6",maHK ="Học kỳ I", diemGiuaKy =2, diemCuoiKy =9, diemTongKet =5.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A1", maHS ="HS7",maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A1", maHS ="HS8",maHK ="Học kỳ I", diemGiuaKy =2, diemCuoiKy =9, diemTongKet =5.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A1", maHS ="HS9",maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =9, diemTongKet =6.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A2", maHS ="HS10",maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A2", maHS ="HS11",maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A2", maHS ="HS12",maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A1", maHS ="HS13",maHK ="Học kỳ I", diemGiuaKy =2, diemCuoiKy =9, diemTongKet =5.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A1", maHS ="HS14",maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A1", maHS ="HS15",maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A2", maHS ="HS16",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A2", maHS ="HS17",maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A2", maHS ="HS18",maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},

                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A1", maHS ="HS1",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A1", maHS ="HS2",maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A1", maHS ="HS3",maHK ="Học kỳ II", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A2", maHS ="HS4",maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A2", maHS ="HS5",maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L10A2", maHS ="HS6",maHK ="Học kỳ II", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A1", maHS ="HS7",maHK ="Học kỳ II", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A1", maHS ="HS8",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =6, diemTongKet =6.5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A1", maHS ="HS9",maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A2", maHS ="HS10",maHK ="Học kỳ II", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A2", maHS ="HS11",maHK ="Học kỳ II", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L11A2", maHS ="HS12",maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A1", maHS ="HS13",maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A1", maHS ="HS14",maHK ="Học kỳ II", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A1", maHS ="HS15",maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =5, diemTongKet =7},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A2", maHS ="HS16",maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A2", maHS ="HS17",maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                  new SBTeacher { maGiaoVien = "GVLY", maLop = "2024L12A2", maHS ="HS18",maHK ="Học kỳ II", diemGiuaKy =1, diemCuoiKy =1, diemTongKet =1},

                  //
                  new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =10, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =10, diemTongKet =10},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =5, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =5, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =5, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},

                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =4, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =8, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =5, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =6, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =6, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =5, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =9, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =5, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =4, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},

                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =10, diemTongKet =10},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =8, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =10, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =6, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =8, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =10, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =6, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},

                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =5, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =10, diemTongKet =10},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =6, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =6, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =5, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},

                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =6, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =10, diemTongKet =10},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =4, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =10, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =4, diemTongKet =4.5},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =8, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVSINH", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =5, diemTongKet =4.5},

                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =7, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =7, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =8, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =4, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =8, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =4, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =9, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                new SBTeacher { maGiaoVien = "GVANH", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},

                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =10, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =5, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =5, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =8, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =5, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =6, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =10, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVCD", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =5, diemTongKet =6},

                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =5, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =9, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =5, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =8, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =4, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =10, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =6, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =10, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =4, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =10, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVCN", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},

                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =7, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =5, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =4, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =5, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =6, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =7, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =4, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =4, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =6, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =5, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =4, diemTongKet =4},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVQP", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},

                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =6, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =5, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =5, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVTC", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},

                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =9, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =9, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =5, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =7, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =6, diemTongKet =5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =8, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ I", diemGiuaKy =9, diemCuoiKy =5, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =5, diemTongKet =5.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ I", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ I", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ I", diemGiuaKy =5, diemCuoiKy =10, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ I", diemGiuaKy =4, diemCuoiKy =8, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVTIN", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ I", diemGiuaKy =8, diemCuoiKy =5, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},

                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =10, diemTongKet =10},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},

                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =7, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =7, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},

                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =7, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVHOA", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},

                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =9, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =10, diemTongKet =10},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =9, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =8, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVVAN", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},

                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =7, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =7, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =8, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =7, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =10, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =6, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =7, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVSU", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},

                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS1", maHK ="Học kỳ II", diemGiuaKy =7, diemCuoiKy =10, diemTongKet =8.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS2", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =9, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A1", maHS ="HS3", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =6, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS4", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS5", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =9, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L10A2", maHS ="HS6", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =7, diemTongKet =7.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS7", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS8", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =9, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A1", maHS ="HS9", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =7, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS10", maHK ="Học kỳ II", diemGiuaKy =10, diemCuoiKy =8, diemTongKet =9},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS11", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =8, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L11A2", maHS ="HS12", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =7, diemTongKet =6.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS13", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =8, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS14", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =10, diemTongKet =8},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A1", maHS ="HS15", maHK ="Học kỳ II", diemGiuaKy =6, diemCuoiKy =6, diemTongKet =6},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS16", maHK ="Học kỳ II", diemGiuaKy =9, diemCuoiKy =10, diemTongKet =9.5},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS17", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7},
                new SBTeacher { maGiaoVien = "GVDIA", maLop = "2024L12A2", maHS ="HS18", maHK ="Học kỳ II", diemGiuaKy =8, diemCuoiKy =6, diemTongKet =7}
                };
            return bangDiemGVs;
        }
    }
}
